Update build workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,85 +1,120 @@
-name: build
+name: Golang build and release
 
 on:
   push:
     tags:
-      - v*
-    branches:
-      - master
-      - develop
+      - 'v*'
   pull_request:
-    branches: [ master ]
+  workflow_dispatch:
+    inputs:
+      tag_name:
+        description: 'Release Tag'
+        required: true
+        default: 'v0.0.0'
 
 jobs:
   build:
     name: Build
-    runs-on: ubuntu-latest
+    runs-on: ${{ matrix.os }}
+
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ubuntu-22.04]
+        go: ["1.21.6"]
+        goos: [linux, freebsd, windows]
+        goarch: [amd64, arm64, 386]
+
     steps:
-    - name: Set up Go 1.x
-      uses: actions/setup-go@v4
-      with:
-        go-version: 1.21.6
-
-    - name: Check out code into the Go module directory
-      uses: actions/checkout@v3
-
-    # https://github.com/golangci/golangci-lint-action
-    - name: Lint
-      uses: golangci/golangci-lint-action@v3
-      with:
-        # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
-        version: v1.55.2
-
-        # Optional: working directory, useful for monorepos
-        # working-directory: somedir
-
-        # Optional: golangci-lint command line arguments.
-        # args: --issues-exit-code=0
-        args: --config=.golangci.yml
-
-        # Optional: show only new issues if it's a pull request. The default value is `false`.
-        only-new-issues: false
-
-    - name: Get dependencies
-      run: |
-        go get -v -t -d ./...
-
-    - name: Test
-      run: go test -v ./...
-
-    - name: Update coverage report
-      uses: ncruces/go-coverage-report@main
-
-    - name: Build
-      run: go build -v ./cmd/gorcon
-
-  docker-release:
-    name: Docker Release
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
+      # Checkout the repository
+      - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v2
-
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
-
-      - name: Login to Docker Hub
-        uses: docker/login-action@v2
+      # Setup Go environment
+      - name: Setup Go
+        uses: actions/setup-go@v5
         with:
-          username: outdead
-          password: ${{ secrets.GORCON_DOCKER_TOKEN }}
-      
-      - name: Build and publish
-        uses: docker/build-push-action@v4
+          go-version: ${{ matrix.go }}
+
+      # Download dependencies
+      - name: Download Go modules
+        env:
+          CGO_ENABLED: 0
+        run: |
+          go mod download
+
+      # Install necessary tools
+      - name: Install dependencies
+        run: |
+          sudo apt -y install git curl gcc musl-dev gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
+
+      # Build the binaries
+      - name: Build binaries
+        env:
+          GOARCH: ${{ matrix.goarch }}
+          CGO_ENABLED: 0
+          GOOS: ${{ matrix.goos }}
+        run: |
+          mkdir -p dist
+          go build -ldflags "-s -w -X main.ServiceVersion=${{ github.ref_name || inputs.tag_name }}" \
+          -o dist/gorcon-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/gorcon
+
+      # Verify build output
+      - name: Verify build output
+        run: |
+          if [ ! -f "dist/gorcon-${{ matrix.goos }}-${{ matrix.goarch }}" ]; then
+            echo "Build output is missing!"
+            exit 1
+          fi
+          echo "Build completed successfully."
+
+      # Append .EXE to Windows binary
+      - name: Append .EXE to windows binary
+        run: |
+          if [ "${{ matrix.goos }}" == "windows" ]; then
+            cd dist/
+            mv gorcon-${{ matrix.goos }}-${{ matrix.goarch }} gorcon-${{ matrix.goos }}-${{ matrix.goarch }}.exe
+            cd ..
+          fi
+
+      # Upload dist folder as an artifact
+      - name: Upload build artifacts
+        uses: actions/upload-artifact@v3
         with:
-          context: .
-          file: build/docker/Dockerfile
-          push: true
-          platforms: linux/amd64,linux/arm64/v8
-          build-args: |
-            VERSION=0.0.0-develop
-          tags: |
-            outdead/rcon:latest
+          name: dist
+          path: dist/
+
+  generate-checksum:
+    name: Generate checksum file
+    runs-on: ubuntu-22.04
+    needs: build
+
+    steps:
+      # Checkout the repository
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      # Download the dist artifact from the build job
+      - name: Download dist artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: dist
+          path: dist
+
+      # Generate checksum.txt
+      - name: Generate checksum.txt
+        run: |
+          cd dist
+          sha256sum * > checksum.txt
+          cd ..
+
+      # Upload all artifacts to GitHub release
+      - name: Upload release artifacts
+        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
+        uses: svenstaro/upload-release-action@v2
+        with:
+          repo_token: ${{ secrets.GITHUB_TOKEN }}
+          file: dist/*
+          tag: ${{ github.ref_name || inputs.tag_name }}
+          overwrite: false
+          file_glob: true
